<?php

/**
 * Project: PHP Gallery
 * Responsibilities:
 *   - Exercise real model SQL without claiming real MySQL concurrency or durability.
 * Repository: https://github.com/klusik/PHP_gallery
 * File: tests/support/admin_operation_fixture.php
 * Module Type: Test Fixture
 * Purpose: Exercise real ledger model SQL through isolated deterministic connection state.
 * Author: Rudolf Klusal
 * Contact: https://github.com/klusik
 * License: MIT License (see LICENSE file in repository)
 * Notes: This is a SQL seam, not evidence of real MySQL concurrency or durability.
 */
declare(strict_types=1);

namespace Gallery\Core;

/** In-memory ledger and separately identified database connections for contention tests. */
final class AdminOperationFixtureDatabase
{
    /**
     * Durable-row simulation shared across connections.
     *
     * @var array<string,array<string,mixed>> Durable-row simulation shared across connections.
     */
    public array $rows = [];
    /**
     * Simulated advisory lock owners.
     *
     * @var array<string,array{connection:int,count:int}> Simulated advisory lock owners.
     */
    public array $locks = [];
    /**
     * Selected fixture connection, independently switchable from actor identity.
     *
     * @var int Selected fixture connection, independently switchable from actor identity.
     */
    public int $connection = 1;
    /**
     * One-shot storage fault category.
     *
     * @var string One-shot storage fault category.
     */
    public string $fault = '';
    /**
     * Independently observed PRIMARY metadata; tests may corrupt it.
     *
     * @var list<array<string,mixed>> Independently observed PRIMARY metadata; tests may corrupt it.
     */
    public array $primaryDefinition = [
        ['COLUMN_NAME' => 'actor_id', 'SEQ_IN_INDEX' => 1, 'NON_UNIQUE' => 0, 'SUB_PART' => null],
        ['COLUMN_NAME' => 'key_hash', 'SEQ_IN_INDEX' => 2, 'NON_UNIQUE' => 0, 'SUB_PART' => null],
    ];
    /**
     * Exact-definition observations, independent of generic existence probes.
     *
     * @var int Exact-definition observations, independent of generic existence probes.
     */
    public int $primaryReads = 0;
    /**
     * Mutation-admission SQL calls; refusals must leave this zero.
     *
     * @var int Mutation-admission SQL calls; refusals must leave this zero.
     */
    public int $claimAttempts = 0;
    /**
     * Operation lock acquisitions attempted after schema preflight.
     *
     * @var int Operation lock acquisitions attempted after schema preflight.
     */
    public int $lockAttempts = 0;

    /**
     * Claims execute outside target transactions in this fixture.
     *
     * @return bool Claims execute outside target transactions in this fixture.
     */
    public function inTransaction(): bool { return false; }

    /**
     * Prepare one statement consumed by the real model.
     * @param string $sql SQL generated by the production model.
     * @return AdminOperationFixtureStatement Isolated statement execution seam.
     */
    public function prepare(string $sql): AdminOperationFixtureStatement
    {
        return new AdminOperationFixtureStatement($this, $sql);
    }

    /**
     * Execute a parameter-free query through the same isolated seam.
     * @param string $sql Production model query.
     * @return AdminOperationFixtureStatement Executed fixture statement.
     */
    public function query(string $sql): AdminOperationFixtureStatement
    {
        $statement = $this->prepare($sql);
        $statement->execute();
        return $statement;
    }
}

/** Deterministic execution of only the production operation-ledger SQL vocabulary. */
final class AdminOperationFixtureStatement
{
    /**
     * Selected scalar or row.
     *
     * @var int|string|array<array-key,mixed>|false|null Selected lock/database scalar, ledger row, metadata page or absent-result marker.
     */
    private mixed $result = false;
    /**
     * Rows changed by this fixture statement.
     *
     * @var int Rows changed by this fixture statement.
     */
    private int $affected = 0;

    /**
     * Bind one SQL statement to the selected fixture database.
     * @param AdminOperationFixtureDatabase $database Shared isolated ledger.
     * @param string $sql Exact production statement.
     * @return void
     */
    public function __construct(private AdminOperationFixtureDatabase $database, private string $sql) {}

    /**
     * Execute a supported statement without connecting to any database.
     * @param array<int,mixed> $parameters Prepared model parameters.
     * @return bool True on fixture execution; injected faults throw.
     */
    public function execute(array $parameters = []): bool
    {
        $database = $this->database;
        if (str_starts_with($this->sql, 'SELECT COLUMN_NAME, SEQ_IN_INDEX, NON_UNIQUE, SUB_PART FROM information_schema.STATISTICS')) {
            ++$database->primaryReads;
            if ($database->fault === 'primary_unknown') {
                throw new \RuntimeException('Private fixture database inspection failure.');
            }
            if ($parameters !== ['admin_operation_keys', 'PRIMARY'] || !str_contains($this->sql, 'TABLE_SCHEMA = DATABASE()')
                || !str_ends_with($this->sql, 'ORDER BY SEQ_IN_INDEX LIMIT 3')) {
                throw new \RuntimeException('PRIMARY observation lost schema identity, order or bounded lookahead.');
            }
            $this->result = array_slice($database->primaryDefinition, 0, 3);
        } elseif (str_starts_with($this->sql, 'SELECT COUNT(*) FROM galleries')) {
            $parent = (int) ($parameters[0] ?? 0);
            $count = 0;
            foreach ($GLOBALS['operation_fixture_galleries'] ?? [] as $gallery) {
                $count += (int) ($gallery['parent_id'] ?? 0) === $parent ? 1 : 0;
            }
            $this->result = $count;
        } elseif ($this->sql === 'SELECT DATABASE()') {
            $this->result = 'disposable_operation_fixture';
        } elseif (str_starts_with($this->sql, 'SELECT GET_LOCK')) {
            ++$database->lockAttempts;
            $name = $parameters[0];
            $lock = $database->locks[$name] ?? null;
            if ($lock && $lock['connection'] !== $database->connection) {
                $this->result = 0;
            } else {
                $database->locks[$name] = ['connection' => $database->connection, 'count' => ($lock['count'] ?? 0) + 1];
                $this->result = 1;
            }
        } elseif (str_starts_with($this->sql, 'SELECT RELEASE_LOCK')) {
            $name = $parameters[0];
            if (($database->locks[$name]['connection'] ?? null) === $database->connection && --$database->locks[$name]['count'] === 0) {
                unset($database->locks[$name]);
            }
            $this->result = 1;
        } elseif (str_starts_with($this->sql, 'INSERT INTO admin_operation_keys')) {
            ++$database->claimAttempts;
            if ($database->fault === 'claim') {
                $database->fault = '';
                throw new \RuntimeException('private-dsn password=fixture-secret');
            }
            [$actor, $key, $operation, $payload, $owner, $created, $updated] = $parameters;
            $identity = $actor . ':' . $key;
            $database->rows[$identity] ??= ['actor_id' => $actor, 'key_hash' => $key, 'operation_name' => $operation, 'payload_hash' => $payload, 'owner_hash' => $owner, 'state' => 'pending', 'response_json' => null, 'created_at' => $created, 'updated_at' => $updated];
        } elseif (str_starts_with($this->sql, 'SELECT COALESCE(SUM(state')) {
            $this->result = ['pending' => 0, 'needs_reconciliation' => 0, 'unknown' => 0];
            foreach ($database->rows as $row) {
                if ($row['state'] !== 'completed') {
                    ++$this->result[in_array($row['state'], ['pending', 'needs_reconciliation'], true) ? $row['state'] : 'unknown'];
                }
            }
        } elseif (str_contains($this->sql, 'ORDER BY actor_id, key_hash LIMIT')) {
            $rows = array_values(array_filter($database->rows,
                /** Select retained non-completed rows beyond the requested keyset cursor. @param array{actor_id:int,key_hash:string,state:string} $row Candidate fixture identity/state. @return bool Whether the row belongs to this pending page. */
                static fn (array $row): bool => $row['state'] !== 'completed'
                && ($row['actor_id'] > $parameters[0] || ($row['actor_id'] === $parameters[1] && strcmp($row['key_hash'], $parameters[2]) > 0))));
            usort($rows,
                /** Reproduce the model's actor/hash keyset ordering. @param array{actor_id:int,key_hash:string} $left Left retained identity. @param array{actor_id:int,key_hash:string} $right Right retained identity. @return int Lexicographic identity comparison. */
                static fn (array $left, array $right): int => ($left['actor_id'] <=> $right['actor_id']) ?: strcmp($left['key_hash'], $right['key_hash']));
            $this->result = array_slice($rows, 0, \Gallery\Core\ADMIN_OPERATION_PENDING_PAGE_SIZE + 1);
        } elseif (str_starts_with($this->sql, 'SELECT actor_id')) {
            $this->result = $database->rows[$parameters[0] . ':' . $parameters[1]] ?? false;
        } elseif (str_contains($this->sql, "SET state = 'completed'")) {
            if (!empty($GLOBALS['operation_fixture_expect_writer']) && ($GLOBALS['operation_fixture_writer_depth'] ?? 0) < 1) {
                throw new \RuntimeException('Upload completion was stored after releasing writer exclusion.');
            }
            if ($database->fault === 'complete_before') {
                $database->fault = '';
                throw new \RuntimeException('private complete failure');
            }
            [$json, $updated, $actor, $key, $operation, $payload, $owner] = $parameters;
            $row = &$database->rows[$actor . ':' . $key];
            if ($row && $row['operation_name'] === $operation && $row['payload_hash'] === $payload && $row['owner_hash'] === $owner && in_array($row['state'], ['pending', 'needs_reconciliation'], true)) {
                $row['state'] = 'completed';
                $row['response_json'] = $json;
                $row['updated_at'] = $updated;
                $this->affected = 1;
            }
            if ($database->fault === 'complete_after_ack') {
                $database->fault = '';
                throw new \RuntimeException('Simulated lost commit acknowledgement');
            }
        } elseif (str_contains($this->sql, "SET state = 'needs_reconciliation'")) {
            [$updated, $actor, $key, $owner] = $parameters;
            $row = &$database->rows[$actor . ':' . $key];
            if ($row && $row['state'] === 'pending' && $row['owner_hash'] === $owner) {
                $row['state'] = 'needs_reconciliation';
                $row['updated_at'] = $updated;
                $this->affected = 1;
            }
        } else {
            throw new \RuntimeException('Unexpected SQL in operation fixture.');
        }
        return true;
    }

    /**
     * Simulated scalar query result.
     *
     * @return int|string|false|null Database name, advisory-lock result or absent scalar in the supported SQL vocabulary.
     */
    public function fetchColumn(): mixed { return $this->result; }
    /**
     * Simulated selected ledger row.
     *
     * @return array<string,mixed>|false Simulated selected ledger row.
     */
    public function fetch(): array|false { return is_array($this->result) ? $this->result : false; }
    /**
     * Bounded simulated result rows for maintenance listing.
     *
     * @return list<array<string,mixed>> Bounded simulated result rows for maintenance listing.
     */
    public function fetchAll(): array { return is_array($this->result) ? $this->result : []; }
    /**
     * Simulated affected-row count.
     *
     * @return int Simulated affected-row count.
     */
    public function rowCount(): int { return $this->affected; }
}

/**
 * Isolated test storage; never application PDO.
 *
 * @return AdminOperationFixtureDatabase Isolated test storage; never application PDO.
 */
function db(): AdminOperationFixtureDatabase { return $GLOBALS['operation_fixture_db']; }
