<?php
/**
 * Project: PHP Gallery
 * Repository: https://github.com/klusik/PHP_gallery
 * File: tests/support/gallery_workflow_safety.php
 * Module Type: Test Fixture
 * Purpose: Enforce workflow fixture ownership and opt-in guards.
 * Responsibilities:
 *   - Reject unsafe paths and configuration before fixture side effects.
 * Author: Rudolf Klusal
 * Disposable integration-fixture ownership and opt-in guards.
 */
declare(strict_types=1);

/** Safety checks shared by the disposable workflow runner and its regression tests. */
namespace GalleryWorkflow;

use RuntimeException;

/** Throw a bounded assertion message without including application or connection data. */
function check(bool $condition, string $message): void
{
    if (!$condition) {
        throw new RuntimeException($message);
    }
}

/** No application config, arbitrary DSN, existing database, or default MySQL port is accepted. */
function databaseOptions(array $environment): array
{
    check(($environment['GALLERY_WORKFLOW_ENABLE'] ?? '') === 'disposable-only', 'Explicit disposable database opt-in is required.');
    check(($environment['GALLERY_WORKFLOW_DB_HOST'] ?? '') === '127.0.0.1', 'The disposable database must use literal IPv4 loopback.');
    $port = filter_var($environment['GALLERY_WORKFLOW_DB_PORT'] ?? '', FILTER_VALIDATE_INT);
    check(is_int($port) && $port >= 1024 && $port <= 65535 && $port !== 3306, 'A dedicated non-default database port is required.');
    check(($environment['GALLERY_WORKFLOW_DB_USER'] ?? '') === 'gallery_workflow_runner', 'A dedicated workflow database principal is required.');
    check(strlen((string) ($environment['GALLERY_WORKFLOW_DB_PASSWORD'] ?? '')) >= 16, 'A nonempty dedicated database password of at least 16 characters is required.');
    check(empty($environment['GALLERY_WORKFLOW_DB_NAME']) && empty($environment['GALLERY_WORKFLOW_DSN']), 'Database names and DSNs are generated by the runner.');
    return ['host' => '127.0.0.1', 'port' => $port, 'user' => 'gallery_workflow_runner',
        'password' => $environment['GALLERY_WORKFLOW_DB_PASSWORD'], 'charset' => 'utf8mb4'];
}

/** Accept only a runner-generated database name. */
function validateDatabaseName(string $name): void
{
    check(preg_match('/^gallery_workflow_[a-f0-9]{24}$/D', $name) === 1, 'Invalid disposable database identity.');
}

/** Connect only to the generated, owned database after checking the explicit opt-in again. */
function fixtureDatabase(string $directory, string $token): \PDO
{
    $directory = validateFixture($directory, $token);
    $options = databaseOptions(getenv());
    $configuration = require $directory . '/config.php';
    check($configuration['database'] === $options + ['name' => 'gallery_workflow_' . $token], 'Fixture database configuration mismatch.');
    $dsn = 'mysql:host=127.0.0.1;port=' . $options['port'] . ';dbname=gallery_workflow_' . $token . ';charset=utf8mb4';
    $pdo = new \PDO($dsn, $options['user'], $options['password'],
        [\PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION, \PDO::ATTR_EMULATE_PREPARES => false]);
    check($pdo->query('SELECT DATABASE()')->fetchColumn() === 'gallery_workflow_' . $token, 'Connected database identity mismatch.');
    return $pdo;
}

/** Require a direct temporary-directory child and an exact ownership marker before cleanup/use. */
function validateFixture(string $directory, string $token): string
{
    check(preg_match('/^[a-f0-9]{24}$/D', $token) === 1, 'Invalid fixture ownership token.');
    $resolved = realpath($directory);
    $temporary = realpath(sys_get_temp_dir());
    check(is_string($resolved) && is_string($temporary) && !is_link($directory), 'Fixture directory is unavailable or linked.');
    check(strcasecmp(dirname($resolved), $temporary) === 0 && basename($resolved) === 'gallery-workflow-' . $token,
        'Fixture must be a uniquely owned direct child of the system temporary directory.');
    check(is_file($resolved . '/.workflow-owner') && !is_link($resolved . '/.workflow-owner')
        && hash_equals($token, (string) file_get_contents($resolved . '/.workflow-owner')), 'Fixture ownership marker does not match.');
    return $resolved;
}

/** Unlink links themselves, never follow them while removing this runner-owned directory. */
function removeFixture(string $directory, string $token): void
{
    $directory = validateFixture($directory, $token);
    $iterator = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($directory,
        \FilesystemIterator::SKIP_DOTS), \RecursiveIteratorIterator::CHILD_FIRST);
    foreach ($iterator as $entry) {
        if ($entry->getPathname() === $directory . DIRECTORY_SEPARATOR . '.workflow-owner') continue;
        $ok = $entry->isLink() || !$entry->isDir() ? @unlink($entry->getPathname()) : @rmdir($entry->getPathname());
        check($ok, 'Disposable fixture cleanup failed.');
    }
    check(@unlink($directory . '/.workflow-owner'), 'Disposable fixture marker cleanup failed.');
    check(@rmdir($directory), 'Disposable fixture directory cleanup failed.');
}
