<?php

/**
 * Project: PHP Gallery
 * Repository: https://github.com/klusik/PHP_gallery
 *
 * File: database/migrations/202605080001_telemetry_thumbnail_variants.php
 * Module Type: Database Migration
 *
 * Purpose:
 *   Aligns telemetry media variant enums with the responsive thumbnail sizes generated by the gallery.
 *
 * Responsibilities:
 *   - Allow telemetry to store the 1280 px thumbnail variant
 *   - Keep existing anonymous telemetry rows valid
 *   - Avoid changing collection semantics outside media variant normalization
 *
 * Author:
 *   Rudolf Klusal
 *
 * Contact:
 *   https://github.com/klusik
 *
 * License:
 *   MIT License (see LICENSE file in repository)
 *
 * Notes:
 *   - Keep comments and docstrings intact when modifying this file.
 *   - Prefer small, readable changes over broad rewrites.
 *
 * Last Updated:
 *   2026-05-08
 */

$mediaVariantEnum = "ENUM('original','thumb_300','thumb_600','thumb_800','thumb_960','thumb_1200','thumb_1280','thumb_1600','webp','jpg','unknown') NOT NULL DEFAULT 'unknown'";

return [
    "ALTER TABLE telemetry_events MODIFY media_variant {$mediaVariantEnum}",
    "ALTER TABLE telemetry_hourly_metrics MODIFY media_variant {$mediaVariantEnum}",
    "ALTER TABLE telemetry_daily_metrics MODIFY media_variant {$mediaVariantEnum}",
];
