<?php

/**
 * Project: PHP Gallery
 * Repository: https://github.com/klusik/PHP_gallery
 *
 * File: app/views/admin_public_inline.php
 * Module Type: View
 *
 * Purpose:
 *   Renders Admin photo-edit presentation used by public inline workflows.
 *
 * Responsibilities:
 *   - Render the full photo editor and read-only AI metadata panel
 *   - Render presentation-only visibility, EXIF, tag, rating, and thumbnail-bound controls
 *   - Keep request handling, authorization, persistence, feature policy, and metadata lookup in controllers
 *
 * Author:
 *   Rudolf Klusal
 *
 * Notes:
 *   - Keep comments and docstrings intact when modifying this file.
 *   - No request globals or persistence access belong in this view.
 *
 * Last Updated:
 *   2026-09-13
 */

declare(strict_types=1);

namespace Gallery\Views;

use function Gallery\Core\e;
use function Gallery\Core\render_footer;
use function Gallery\Core\render_header;
use function Gallery\Services\t;

/** @param array<string,mixed>|null $viewModel Controller-prepared AI metadata state. */
function view_render_admin_image_ai_metadata_panel(?array $viewModel): void
{
    if ($viewModel === null || empty($viewModel['enabled'])) {
        return;
    }

    echo '<div class="admin-ai-metadata-panel"><h2>' . e(t('admin.gallery_editor.ai_metadata_title', 'Internal AI metadata')) . '</h2>';
    if (empty($viewModel['schema_ready'])) {
        echo '<p class="muted">' . e(t('admin.gallery_editor.ai_metadata_migration_hidden', 'AI metadata inspection will be available after the AI image-analysis migration is applied.')) . '</p></div>';
        return;
    }

    echo '<p class="muted">' . e(t('admin.gallery_editor.ai_metadata_help', 'Read-only metadata generated by the Windows AI worker. This is used for search and indexing, not as the public photo description.')) . '</p>';
    if (empty($viewModel['has_metadata'])) {
        echo '<p class="muted">' . e(t('admin.gallery_editor.ai_metadata_empty', 'No AI metadata has been generated for this photo yet.')) . '</p></div>';
        return;
    }

    echo '<dl class="admin-ai-metadata-facts">';
    echo '<dt>' . e(t('admin.gallery_editor.ai_metadata_model', 'Model')) . '</dt><dd>' . e((string) ($viewModel['model_label'] ?? t('admin.gallery_editor.unknown', 'Unknown'))) . '</dd>';
    echo '<dt>' . e(t('admin.gallery_editor.ai_metadata_generated', 'Generated')) . '</dt><dd>' . e((string) ($viewModel['generated_at'] ?? t('admin.gallery_editor.unknown', 'Unknown'))) . '</dd>';
    echo '<dt>' . e(t('admin.gallery_editor.ai_metadata_source', 'Source')) . '</dt><dd>' . e((string) ($viewModel['source_summary'] ?? t('admin.gallery_editor.unknown', 'Unknown'))) . '</dd>';
    echo '</dl>';
    echo '<label>' . e(t('admin.gallery_editor.ai_metadata_searchable_text', 'Searchable internal text')) . '<textarea readonly rows="5">' . e((string) ($viewModel['searchable_text'] ?? '')) . '</textarea></label>';
    echo '<label>' . e(t('admin.gallery_editor.ai_metadata_raw_json', 'Raw metadata JSON')) . '<textarea readonly rows="10">' . e((string) ($viewModel['raw_json'] ?? '')) . '</textarea></label></div>';
}

/** @param array<string,mixed> $state Controller-prepared thumbnail-bound slider state. */
function view_render_admin_image_thumbnail_bounds(array $state): void
{
    $values = array_values(array_map('intval', (array) ($state['values'] ?? [])));
    if (!$values) {
        return;
    }
    $minIndex = (int) ($state['min_index'] ?? 0);
    $maxIndex = (int) ($state['max_index'] ?? count($values) - 1);
    echo '<div class="admin-thumbnail-bound-control" data-thumbnail-bound-control data-thumbnail-bound-values="' . e(implode(',', $values)) . '">';
    echo '<div class="admin-thumbnail-bound-header"><div><h3>' . e(t('admin.gallery_editor.thumbnail_bounds_title', 'Responsive thumbnail quality bounds')) . '</h3><p class="muted">' . e(t('admin.gallery_editor.thumbnail_bounds_help', 'Optional per-photo guardrails. These can override gallery-level guardrails when the public selection logic is wired in the next step.')) . '</p></div><strong data-thumbnail-bound-summary>' . e(t('thumbnail_bounds.auto', 'Auto')) . '</strong></div>';
    echo '<div class="admin-thumbnail-bound-valuebar" aria-hidden="true"><span><small>' . e(t('thumbnail_bounds.min', 'Min')) . '</small><b data-thumbnail-bound-min-display>' . e(t('thumbnail_bounds.auto_min', 'Auto min')) . '</b></span><span><small>' . e(t('thumbnail_bounds.max', 'Max')) . '</small><b data-thumbnail-bound-max-display>' . e(t('thumbnail_bounds.auto_max', 'Auto max')) . '</b></span></div>';
    echo '<div class="admin-thumbnail-bound-slider" aria-label="' . e(t('admin.gallery_editor.thumbnail_bounds_title', 'Responsive thumbnail quality bounds')) . '"><div class="admin-thumbnail-bound-rail" aria-hidden="true"></div>';
    echo '<input type="range" min="0" max="' . (count($values) - 1) . '" step="1" value="' . $minIndex . '" data-thumbnail-bound-min-index aria-label="' . e(t('thumbnail_bounds.minimum_size', 'Minimum thumbnail size')) . '">';
    echo '<input type="range" min="0" max="' . (count($values) - 1) . '" step="1" value="' . $maxIndex . '" data-thumbnail-bound-max-index aria-label="' . e(t('thumbnail_bounds.maximum_size', 'Maximum thumbnail size')) . '"></div>';
    echo '<input type="hidden" name="image_thumbnail_min_size" value="' . (int) $values[$minIndex] . '" data-thumbnail-bound-min-value><input type="hidden" name="image_thumbnail_max_size" value="' . (int) $values[$maxIndex] . '" data-thumbnail-bound-max-value></div>';
}

/** @param array<string,mixed> $viewModel Controller-prepared full image editor state. */
function view_render_admin_edit_image(array $viewModel): void
{
    $image = (array) ($viewModel['image'] ?? []);
    render_header(t('admin.gallery_editor.edit_image', 'Edit image'));
    echo '<section class="panel"><h1>' . e(t('admin.gallery_editor.edit_image', 'Edit image')) . '</h1><p><img decoding="async" loading="lazy" src="' . e((string) ($viewModel['thumbnail_url'] ?? '')) . '" alt=""></p>';
    echo '<form method="post" class="form-grid">' . (string) ($viewModel['csrf_html'] ?? '');
    echo '<input type="hidden" name="id" value="' . (int) ($image['id'] ?? 0) . '">';
    echo '<label>' . e(t('admin.gallery_editor.title', 'Title')) . '<input name="title" value="' . e((string) ($image['title'] ?? '')) . '"></label>';
    echo '<label>' . e(t('admin.gallery_editor.description', 'Description')) . '<textarea name="description" data-openai-description-textarea>' . e((string) ($image['description'] ?? '')) . '</textarea></label>';
    $formModel = is_array($viewModel['form_model'] ?? null) ? $viewModel['form_model'] : [];
    view_render_content_localization_fields('image', $image, $formModel);
    if (function_exists(__NAMESPACE__ . '\\view_render_admin_openai_text_assist_tool')) {
        view_render_admin_openai_text_assist_tool((int) ($image['gallery_id'] ?? 0), (int) ($image['id'] ?? 0), 'image', $formModel);
    }
    echo '<label>' . e(t('admin.gallery_editor.visibility', 'Visibility')) . '<select name="visibility">';
    foreach (['draft', 'public', 'private'] as $visibility) {
        echo '<option value="' . e($visibility) . '"' . ((string) ($image['visibility'] ?? '') === $visibility ? ' selected' : '') . '>' . e($visibility) . '</option>';
    }
    echo '</select></label>';

    if (!empty($viewModel['nsfw_ready'])) {
        echo '<input type="hidden" name="nsfw_field_present" value="1"><label><input type="checkbox" name="nsfw_enabled" value="1"' . ((int) ($image['nsfw_enabled'] ?? 0) === 1 ? ' checked' : '') . '> ' . e(t('admin.gallery_editor.mark_photo_nsfw', 'Mark this photo as NSFW / 18+')) . '</label>';
        echo '<p class="muted">' . e(t('admin.gallery_editor.photo_nsfw_help', 'When enabled, anonymous visitors must confirm they are 18+ before this photo, thumbnail, or original media file is served. Before using NSFW content, please verify that your hosting provider or web hosting plan permits it, as adult content may violate their policies.')) . '</p>';
    }
    echo '<label>' . e(t('admin.gallery_editor.sort_order', 'Sort order')) . '<input name="sort_order" type="number" value="' . (int) ($image['sort_order'] ?? 0) . '"></label>';

    if (!empty($viewModel['smart_gallery_ready'])) {
        echo '<label>' . e(t('smart_gallery.editorial_rating', 'Editorial rating')) . '<select name="editorial_rating"><option value="0">' . e(t('smart_gallery.unrated', 'Unrated')) . '</option>';
        for ($ratingOption = 1; $ratingOption <= 5; $ratingOption++) {
            echo '<option value="' . $ratingOption . '"' . ((int) ($image['editorial_rating'] ?? 0) === $ratingOption ? ' selected' : '') . '>' . e(t('smart_gallery.rating_stars', '{count} stars', ['count' => $ratingOption])) . '</option>';
        }
        echo '</select><span class="muted">' . e(t('smart_gallery.rating_private_help', 'Private editorial metadata used by Smart Gallery rules; unrelated to visitor voting.')) . '</span></label>';
    }

    if (!empty($viewModel['thumbnail_bounds_ready'])) {
        view_render_admin_image_thumbnail_bounds((array) ($viewModel['thumbnail_bounds'] ?? []));
    } else {
        echo '<p class="muted">' . e(t('admin.gallery_editor.thumbnail_bounds_migration_required', 'Thumbnail quality bounds will be available after the database migration is applied.')) . '</p>';
    }

    echo '<label>' . e(t('admin.gallery_editor.tags', 'Tags')) . '<input name="tags" value="' . e((string) ($viewModel['tag_names'] ?? '')) . '" list="tag-suggestions" data-tag-input><span class="muted">' . e(t('admin.gallery_editor.tags_help', 'Separate tags with commas.')) . '</span></label>';
    echo '<datalist id="tag-suggestions">';
    foreach ((array) ($viewModel['tag_suggestions'] ?? []) as $name) {
        echo '<option value="' . e((string) $name) . '"></option>';
    }
    echo '</datalist>';

    if (!empty($viewModel['exif_ready'])) {
        echo '<div class="exif-admin-summary"><h2>' . e(t('admin.gallery_editor.exif_gps', 'EXIF / GPS')) . '</h2><dl>';
        echo '<dt>' . e(t('admin.gallery_editor.taken', 'Taken')) . '</dt><dd>' . e((string) ($image['exif_taken_at'] ?? '')) . '</dd>';
        echo '<dt>' . e(t('admin.gallery_editor.camera', 'Camera')) . '</dt><dd>' . e(trim((string) ($image['exif_camera_make'] ?? '') . ' ' . (string) ($image['exif_camera_model'] ?? ''))) . '</dd>';
        echo '<dt>' . e(t('admin.gallery_editor.lens', 'Lens')) . '</dt><dd>' . e((string) ($image['exif_lens_model'] ?? '')) . '</dd>';
        echo '<dt>' . e(t('admin.gallery_editor.exposure', 'Exposure')) . '</dt><dd>' . e(trim((string) ($image['exif_focal_length'] ?? '') . ' ' . (string) ($image['exif_aperture'] ?? '') . ' ' . (string) ($image['exif_exposure_time'] ?? '') . ' ISO ' . (string) ($image['exif_iso'] ?? ''))) . '</dd>';
        echo '<dt>' . e(t('admin.gallery_editor.gps', 'GPS')) . '</dt><dd>' . (!empty($viewModel['has_gps']) ? e((string) ($image['gps_lat'] ?? '') . ', ' . (string) ($image['gps_lng'] ?? '')) : e(t('admin.gallery_editor.no_gps', 'No GPS coordinates found'))) . '</dd>';
        echo '</dl><p class="muted">' . e(t('admin.gallery_editor.exif_refresh_hint', 'EXIF and GPS values are refreshed when the image is scanned again.')) . '</p></div>';
    }
    view_render_admin_image_ai_metadata_panel(is_array($viewModel['ai_metadata'] ?? null) ? $viewModel['ai_metadata'] : null);
    echo '<button type="submit">' . e(t('admin.gallery_editor.save_image', 'Save image')) . '</button></form></section>';
    render_footer();
}
